from importlib.resources import files
import unittest


class WebSurfaceProductTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        root = files("x_reader.web")
        cls.app = root.joinpath("index.html").read_text(encoding="utf-8")
        cls.en = root.joinpath("landing-en.html").read_text(encoding="utf-8")
        cls.zh = root.joinpath("landing-zh.html").read_text(encoding="utf-8")

    def test_landing_pages_have_canonical_hreflang_and_cta(self):
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/en"', self.en)
        self.assertIn('hreflang="zh-CN"', self.en)
        self.assertIn('href="/app"', self.en)
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/zh"', self.zh)
        self.assertIn('hreflang="en"', self.zh)
        self.assertIn('href="/app"', self.zh)

    def test_landing_pages_explain_evidence_contract(self):
        for html in (self.en, self.zh):
            for state in ("PASS", "PARTIAL", "FAIL", "UNKNOWN"):
                self.assertIn(state, html)
            self.assertIn("npx skills add runesleo/x-reader --skill x-reader", html)
            self.assertIn("MCP", html)

    def test_localized_positioning_is_not_literal_duplicate(self):
        self.assertIn("Your AI says it read the source.", self.en)
        self.assertIn("别让 AI 假装读过原文", self.zh)
        self.assertNotEqual(self.en, self.zh)

    def test_app_has_search_social_metadata_and_product_links(self):
        self.assertIn('name="description"', self.app)
        self.assertIn('property="og:title"', self.app)
        self.assertIn('name="twitter:card"', self.app)
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/app"', self.app)
        self.assertIn('href="/en"', self.app)
        self.assertIn('href="/zh"', self.app)

    def test_app_has_output_native_distribution_actions(self):
        self.assertIn('id="copyReceipt"', self.app)
        self.assertIn('id="copyJson"', self.app)
        self.assertIn('id="shareReceipt"', self.app)
        self.assertIn("Generated by x-reader", self.app)

    def test_share_projection_does_not_use_source_preview(self):
        start = self.app.index("function receiptText")
        end = self.app.index("function requireResult")
        share_fn = self.app[start:end]
        self.assertIn("r.status", share_fn)
        self.assertIn("r.evidence", share_fn)
        self.assertIn("componentText(r)", share_fn)
        self.assertNotIn("content_preview", share_fn)

    def test_dynamic_source_fields_are_text_only(self):
        self.assertNotIn("innerHTML", self.app)
        self.assertIn("textContent", self.app)


if __name__ == "__main__":
    unittest.main()
