from importlib.resources import files
import unittest


class WebSurfaceProductTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.html = files("x_reader.web").joinpath("index.html").read_text(encoding="utf-8")

    def test_has_search_and_social_metadata(self):
        self.assertIn('name="description"', self.html)
        self.assertIn('property="og:title"', self.html)
        self.assertIn('name="twitter:card"', self.html)

    def test_has_output_native_distribution_actions(self):
        self.assertIn('id="copyReceipt"', self.html)
        self.assertIn('id="copyJson"', self.html)
        self.assertIn('id="shareReceipt"', self.html)
        self.assertIn("Generated by x-reader", self.html)

    def test_has_zero_install_and_agent_activation_paths(self):
        self.assertIn("Open-source beta · free · no signup", self.html)
        self.assertIn("npx skills add runesleo/x-reader --skill x-reader", self.html)
        self.assertIn("https://github.com/runesleo/x-reader", self.html)

    def test_share_projection_does_not_use_source_preview(self):
        start = self.html.index("function receiptText")
        end = self.html.index("function requireResult")
        share_fn = self.html[start:end]
        self.assertIn("r.status", share_fn)
        self.assertIn("r.evidence", share_fn)
        self.assertIn("componentText(r)", share_fn)
        self.assertNotIn("content_preview", share_fn)

    def test_dynamic_source_fields_are_text_only(self):
        self.assertNotIn("innerHTML", self.html)
        self.assertIn("textContent", self.html)


if __name__ == "__main__":
    unittest.main()
