from importlib.resources import files
import unittest


class WebSurfaceProductTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        root = files("x_reader.web")
        cls.app = root.joinpath("index.html").read_text(encoding="utf-8")
        cls.en = root.joinpath("landing-en.html").read_text(encoding="utf-8")
        cls.zh = root.joinpath("landing-zh.html").read_text(encoding="utf-8")

    def test_landing_pages_have_canonical_hreflang_and_cta(self):
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/en"', self.en)
        self.assertIn('hreflang="zh-CN"', self.en)
        self.assertIn('href="/app"', self.en)
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/zh"', self.zh)
        self.assertIn('hreflang="en"', self.zh)
        self.assertIn('href="/app"', self.zh)

    def test_product_positioning_is_universal_reader_first(self):
        self.assertIn("Universal content reader", self.en)
        self.assertIn("Turn a URL into source content your AI agent can actually use.", self.en)
        self.assertIn("通用内容读取层", self.zh)
        self.assertIn("把一个链接，真正读成 AI 能用的内容。", self.zh)
        self.assertIn("Evidence Receipt is a guardrail", self.en)
        self.assertIn("Evidence Receipt 是 reader 上面的可信度机制", self.zh)

    def test_full_reader_platform_scope_is_visible(self):
        for marker in ("X / Twitter", "YouTube", "Bilibili", "Podcasts", "WeChat", "Xiaohongshu", "Telegram", "RSS"):
            self.assertIn(marker, self.en)
        for marker in ("微信公众号", "小红书", "Telegram", "RSS", "Bilibili"):
            self.assertIn(marker, self.zh)

    def test_hosted_web_is_clearly_a_subset(self):
        self.assertIn("Hosted subset", self.en)
        self.assertIn("Public X, YouTube and generic web URLs", self.en)
        self.assertIn("Hosted 子集", self.zh)
        self.assertIn("当前公开版只处理公开 X、YouTube 和普通网页", self.zh)

    def test_landing_pages_keep_evidence_contract_as_guardrail(self):
        for html in (self.en, self.zh):
            for state in ("PASS", "PARTIAL", "FAIL", "UNKNOWN"):
                self.assertIn(state, html)
            self.assertIn("npx skills add runesleo/x-reader --skill x-reader", html)
            self.assertIn("MCP", html)

    def test_app_has_search_social_metadata_and_product_links(self):
        self.assertIn('name="description"', self.app)
        self.assertIn('property="og:title"', self.app)
        self.assertIn('name="twitter:card"', self.app)
        self.assertIn('rel="canonical" href="https://xreader.leolabs.me/app"', self.app)
        self.assertIn('href="/en"', self.app)
        self.assertIn('href="/zh"', self.app)

    def test_app_has_output_native_distribution_actions(self):
        self.assertIn('id="copyReceipt"', self.app)
        self.assertIn('id="copyJson"', self.app)
        self.assertIn('id="shareReceipt"', self.app)
        self.assertIn("Generated by x-reader", self.app)

    def test_share_projection_does_not_use_source_preview(self):
        start = self.app.index("function receiptText")
        end = self.app.index("function requireResult")
        share_fn = self.app[start:end]
        self.assertIn("r.status", share_fn)
        self.assertIn("r.evidence", share_fn)
        self.assertIn("componentText(r)", share_fn)
        self.assertNotIn("content_preview", share_fn)

    def test_dynamic_source_fields_are_text_only(self):
        self.assertNotIn("innerHTML", self.app)
        self.assertIn("textContent", self.app)


if __name__ == "__main__":
    unittest.main()
